### ISSUE TITLE
deploy di heroku

### ISSUE THREAD

**Issue by mmararief** [febriadj/lk21-api#1]
tidak menemukan hasil apapun saat melakukan get, padahal sudah di ubah envnya

**Comment by febriadj** [comment]
Maaf bisa di screenshot file `.env` nya dan hasil dari GET request yang bermasalah tadi?

**Comment by mmararief** [comment]
Ini om

<img width="1280" alt="Screenshot 2023-04-07 153118" src="https://user-images.githubusercontent.com/94788186/230573746-32352f14-57cb-4e2e-b703-4c2535e9d0a8.png">

<img width="961" alt="Screenshot 2023-04-07 153009" src="https://user-images.githubusercontent.com/94788186/230573779-b585ec1b-d7e5-4e55-a6fe-acb615db2a01.png">

**Comment by mmararief** [comment]
kalo di lokal bi

> Maaf bisa di screenshot file `.env` nya dan hasil dari GET request yang bermasalah tadi?

pas di lokal bisa om pake .env

**Comment by febriadj** [comment]
Disini gk ada yang salah dari settingan env nya dan target URLs nya juga udh terhubung, problem nya ada di Heroku nya

**Comment by mmararief** [comment]
okee terima kasih, ada opsi lain gak ya selain pake hero ku

**Comment by febriadj** [comment]
Saya pakai https://cyclic.sh/

Alternatif Heroku lainnya bisa dicek disini: https://github.com/anandrmedia/heroku-free-alternatives

**Comment by mmararief** [comment]
> https://cyclic.sh/

saya coba di situ kok sama ya mas, env nya udah saya samain juga padahal.

**Comment by febriadj** [comment]
Bisa di screenshot konfigurasi env variables sama server logs nya mas?

**Comment by febriadj** [comment]
Maaf mas, tadi saya sudah coba deploy di environment lain dan ternyata emang scraper nya gk bekerja, tapi environment utamanya: https://lk21-api.cyclic.app masih berjalan normal. Saya coba solving dulu problem ini.

**Comment by mmararief** [comment]
> Maaf mas, tadi saya sudah coba deploy di environment lain dan ternyata emang scraper nya gk bekerja, tapi environment utamanya: https://lk21-api.cyclic.app masih berjalan normal. Saya coba solving dulu problem ini.

Siap om, terima kasih infonya

**Comment by febriadj** [comment]
Cek regions yang dipake di env nya mas, ada beberapa regions yang diblokir sama pihak LK21 nya. Coba deploy ulang terus pake regions Asia/Europe, solusi ini mungkin bisa dipake juga buat di Heroku.

Saya pakai regions **ap-southeast-1**

<img width="300" alt="deployment" src="https://user-images.githubusercontent.com/73212374/230631812-622634d8-7e70-4438-9e24-856997b442f7.png">

**Comment by febriadj** [comment]
Cek regions yang dipake di servernya mas, ada beberapa regions yang diblokir sama pihak LK21 nya. Coba deploy ulang terus pake regions Asia/Europe, solusi ini mungkin bisa dipake juga buat problem di Heroku.

**Asia Pacific (Singapore) - ap-southeast-1**

<img width="400" alt="deployment" src="https://user-images.githubusercontent.com/73212374/230636777-fb4dca0f-008f-4ac0-819c-35b0fad22633.png">

**Comment by mmararief** [comment]
> Cek regions yang dipake di servernya mas, ada beberapa regions yang diblokir sama pihak LK21 nya. Coba deploy ulang terus pake regions Asia/Europe, solusi ini mungkin bisa dipake juga buat problem di Heroku.
> 
> **Asia Pacific (Singapore) - ap-southeast-1**
> 
> <img alt="deployment" width="400" src="https://user-images.githubusercontent.com/73212374/230636777-fb4dca0f-008f-4ac0-819c-35b0fad22633.png">

iya om udah bisa coba pake region eropa, terima kasihh
