### ISSUE TITLE
result null di vercel

### ISSUE THREAD

**Issue by Sisableng** [febriadj/lk21-api#2]
bang maaf ini knapa ya, saya deploy di vercel dan berhasil, cuma untuk get movies dll output nya null terus

biar jalan di vercel saya buat beberapa file
di root `vercel.json`
```
{
  "regions": ["sin1"], //sin1 | ap-southeast-1 | Singapore
  "rewrites": [{ "source": "/(.*)", "destination": "/api" }]
}
```

trus bikin folder `public/.gitkeep` (ini syarat biar bisa deploy ke vercel)
sama `api/index.ts`
```
import server from '../src/server';

export default server;
```

ini di base url aman2 aja `https://apilk21.vercel.app/`

![image](https://github.com/febriadj/lk21-api/assets/58748827/1bd37586-b3b8-489f-bce6-67b3605fdac9)

tapi kalo nyoba `https://apilk21.vercel.app/movies`  response nya null terus

![image](https://github.com/febriadj/lk21-api/assets/58748827/37633f87-71c9-4b3c-b1b8-5b3b77771b32)

region udah saya set ke `Asia/Singapore`

![image](https://github.com/febriadj/lk21-api/assets/58748827/2c885585-1589-4e34-ab68-3269f970d8c4)

mohon pencerahanya min

**Comment by febriadj** [comment]
Baru saya update, coba pakai yg commit terbaru. Untuk link LK21 terbarunya cek di base url.

**Comment by Thevtok** [comment]
tinggal movienya aja yg masih bug,series udah ok ,lanjutkan terus karyamu bang

**Comment by Thevtok** [comment]
ubah env nya jadi link yg pro ,yg nonton drama pake redirect jadi null semua

**Comment by febriadj** [comment]
@Thevtok @Sisableng 

Link Terbaru: https://tv1.nontondrama.click.

```env
LK21_URL = https://tv1.nontondrama.click
ND_URL = https://tv1.nontondrama.click
```

**Comment by Sisableng** [comment]
ok saya soba dulu

**Comment by Sisableng** [comment]
buat di vercel ntah knapa jadi error `This Serverless Function has crashed.`
![Screenshot from 2023-08-21 20-42-26](https://github.com/febriadj/lk21-api/assets/58748827/1dc9889e-ec6a-41a3-9fa9-9df89a71bb3c)


tapi di cyclic skarang berjalan normal, btw mungkin saya salah setup atau gimana, tapi overall jalan di cyclic, makasi bang
